//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int idproducto { get; set; }
        public string name { get; set; }
        public decimal pvp { get; set; }
        public string impuesto { get; set; }
        public bool estado { get; set; }
        public string marca { get; set; }
    }
}
